In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
dataset = pd.read_csv('temp.csv')
print(dataset.columns)
dataset.head()

Index(['Year', 'Month', 'Day', 'Date', 'PPT. ', 'Av temp', 'Tmax', 'Tmin'], dtype='object')


Year  Month  Day        Date  PPT.   Av temp  Tmax  Tmin
0  1901      1    1  01/01/1901    0.0      2.1   3.5   0.6
1  1901      1    2  02/01/1901    0.0      4.0   7.2   0.7
2  1901      1    3  03/01/1901    0.0      3.0   6.7  -0.7
3  1901      1    4  04/01/1901    0.0      3.7   7.9  -0.6
4  1901      1    5  05/01/1901    0.0     -0.3   1.2  -1.7

In [8]:
dataset = dataset.drop(columns='Date')
dataset = dataset.drop(columns='PPT. ')
dataset = dataset.drop(columns='Tmax')
dataset = dataset.drop(columns='Tmin')

In [9]:
dataset.head()

Year  Month  Day  Av temp
0  1901      1    1      2.1
1  1901      1    2      4.0
2  1901      1    3      3.0
3  1901      1    4      3.7
4  1901      1    5     -0.3

In [10]:
data = dataset.iloc[0:10,:].values
print(data)

[[ 1.901e+03  1.000e+00  1.000e+00  2.100e+00]
 [ 1.901e+03  1.000e+00  2.000e+00  4.000e+00]
 [ 1.901e+03  1.000e+00  3.000e+00  3.000e+00]
 [ 1.901e+03  1.000e+00  4.000e+00  3.700e+00]
 [ 1.901e+03  1.000e+00  5.000e+00 -3.000e-01]
 [ 1.901e+03  1.000e+00  6.000e+00 -1.000e-01]
 [ 1.901e+03  1.000e+00  7.000e+00  8.000e-01]
 [ 1.901e+03  1.000e+00  8.000e+00  0.000e+00]
 [ 1.901e+03  1.000e+00  9.000e+00 -4.400e+00]
 [ 1.901e+03  1.000e+00  1.000e+01  1.700e+00]]


In [19]:
def runnian(year):
    flag = False
    if year%4 == 0 and year%100 != 0:
        flag = True
    return flag

def date2index(year, month, day):
    normal = [31,28,31,30,31,30,31,31,30,31,30,31]
    special = [31,29,31,30,31,30,31,31,30,31,30,31]
    if month == 1:
        return int(day - 1)
    else:
        if runnian(year):
            return int(sum(special[0:month-1]) + day - 1)
        else:
            return int(sum(normal[0:month-1]) + day - 1)

In [20]:
temp = {}

for i in data:
    index = date2index(i[0], i[1], i[2])
    temp[index] = []
    temp.append(i[3])

print(temp)

{0: 2.1, 1: 4.0, 2: 3.0, 3: 3.7, 4: -0.3, 5: -0.1, 6: 0.8, 7: 0.0, 8: -4.4, 9: 1.7}
