In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
dataset = pd.read_csv('temp.csv')
print(dataset.columns)
dataset.head()

Index(['Year', 'Month', 'Day', 'Date', 'PPT. ', 'Av temp', 'Tmax', 'Tmin'], dtype='object')


Year  Month  Day        Date  PPT.   Av temp  Tmax  Tmin
0  1901      1    1  01/01/1901    0.0      2.1   3.5   0.6
1  1901      1    2  02/01/1901    0.0      4.0   7.2   0.7
2  1901      1    3  03/01/1901    0.0      3.0   6.7  -0.7
3  1901      1    4  04/01/1901    0.0      3.7   7.9  -0.6
4  1901      1    5  05/01/1901    0.0     -0.3   1.2  -1.7

In [23]:
dataset = dataset.drop(columns='Date')
dataset = dataset.drop(columns='PPT. ')
dataset = dataset.drop(columns='Tmax')
dataset = dataset.drop(columns='Tmin')

In [24]:
dataset.head()

Year  Month  Day  Av temp
0  1901      1    1      2.1
1  1901      1    2      4.0
2  1901      1    3      3.0
3  1901      1    4      3.7
4  1901      1    5     -0.3

In [28]:
data = {}

temp = dataset.iloc[0:3,-1:].values
print(temp)

[[2.1]
 [4. ]
 [3. ]]


In [34]:
for i in dataset.values:
    if i[:][1] == 1 and i[:][2] == 1:
        print(i)

[1.901e+03 1.000e+00 1.000e+00 2.100e+00]
[1.902e+03 1.000e+00 1.000e+00 5.700e+00]
[1.903e+03 1.000e+00 1.000e+00 1.000e+00]
[1.904e+03 1.000e+00 1.000e+00 1.400e+00]
[ 1.905e+03  1.000e+00  1.000e+00 -2.000e-01]
[ 1.906e+03  1.000e+00  1.000e+00 -3.000e-01]
[1.907e+03 1.000e+00 1.000e+00 2.900e+00]
[1.908e+03 1.000e+00 1.000e+00 2.100e+00]
[1.909e+03 1.000e+00 1.000e+00 6.400e+00]
[1.91e+03 1.00e+00 1.00e+00 6.30e+00]
[1.911e+03 1.000e+00 1.000e+00 4.900e+00]
[1.912e+03 1.000e+00 1.000e+00 6.500e+00]
[1.913e+03 1.000e+00 1.000e+00 5.000e+00]
[1.914e+03 1.000e+00 1.000e+00 3.000e-01]
[1.915e+03 1.000e+00 1.000e+00 1.100e+00]
[1.916e+03 1.000e+00 1.000e+00 8.900e+00]
[1.917e+03 1.000e+00 1.000e+00 1.060e+01]
[1.918e+03 1.000e+00 1.000e+00 3.000e-01]
[1.919e+03 1.000e+00 1.000e+00 1.400e+00]
[ 1.92e+03  1.00e+00  1.00e+00 -6.00e-01]
[1.921e+03 1.000e+00 1.000e+00 8.700e+00]
[1.922e+03 1.000e+00 1.000e+00 7.000e+00]
[1.923e+03 1.000e+00 1.000e+00 1.400e+00]
[1.924e+03 1.000e+00 1.000e+00